### ISSUE TITLE
Conflicts during temp directory creation

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace-core#12]
Some books cause the processing to file with a `file already exists` error. For example:

```
Unexpected error: Error: EEXIST: file already exists, mkdir '/Users/charlesl/Documents/Consulting/Macmillan/Updated Files/worldS/file!var!folders!fx!7s517m5s7k5gf65z4gqvt6040000gp!T!tmp-13177VFBRbslHsE6L!OEBPS!xhtml!mck_978145769'
```

**Comment by clapierre** [comment]
Latest version 0.1.2 still has this problem
2014-B-032:Updated Files charlesl$ npm view ace-core
 
{ name: 'ace-core',
  description: 'Ace by DAISY, an Accessibility Checker for EPUB',
  'dist-tags': { latest: '0.1.2' },
  versions: [ '0.1.0', '0.1.2' ],
  maintainers: [ 'rdeltour <rdeltour@gmail.com>' ],

2014-B-032:Updated Files charlesl$ ace -o WorldS -t World "9781319083281 (Understanding World Societies).epub" 
Unzipping...
Parsing EPUB...
Checking documents...
Unexpected error: Error: EEXIST: file already exists, mkdir '/Users/charlesl/Documents/Consulting/Macmillan/Updated Files/World/file!var!folders!fx!7s517m5s7k5gf65z4gqvt6040000gp!T!tmp-77181jUNXiNg3RZn!OEBPS!xhtml!mck_9781457699'

I will email you a link to this book privately.
Charles.
