### ISSUE TITLE
Improve output files creations

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace-core#17]
We could add options to:
- override existing files or not
- clean the entire output directory, or resources sub directories

**Comment by amesga** [comment]
If the output files are created in a subfolder named after the ePub file, a user wouldn't have to change output dirs for each ePub and could keep the -o switch the same when running a batch of books. Right now, I am manually adding each report to a subfolder before running the next book through.

**Comment by rdeltour** [comment]
New features in next version:

- check the presence of existing report files, and abort by default
- `--force` option to override any existing files
- `--subdir` option to create the report in a sub-directory named after the input EPUB
