### ISSUE TITLE
Improve the UX of the violations list

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace-core#27]
The table displaying the violations in the HTML report could probably be improved here and there, for instance:

- the _Impact _ column's size can be reduced, the label could use an icon and color code
- in the _Target_ column, we need to specify when the selectors are a CSS selector or a CFI selectors
- the _Description_ and _KB Link_ columns could be merged to save horizontal space
- the _Engine_ info could be merged in the _Rule_ table

**Comment by marisademeglio** [comment]
The table column sizes and ordering is a bit better if you see https://github.com/daisy/ace-core/pull/25

I agree about labeling 'target' more clearly and merging the columns you mentioned.

**Comment by marisademeglio** [comment]
<img width="2381" alt="screen shot 2017-08-31 at 4 39 41 pm" src="https://user-images.githubusercontent.com/734730/29949645-0ebf97f8-8e6b-11e7-8357-a125f2eb3b04.png">

@rdeltour anything else or can we close this issue?

**Comment by rdeltour** [comment]
LGTM.

I would maybe put the "Impact" column first, with an icon and color code (e.g. red/orange/yello whatever), but that can be left to a 2nd pass of beautification. The table is much more compact and readable I think already!
