### ISSUE TITLE
IMAGES folder outside of output folder

### ISSUE THREAD

**Issue by clapierre** [daisy/ace-core#33]
When I tried the following report
ace -o Anesthesia 9780323508902_epub.epub
A Anesthesia directory was created which I was expecting but at the same directory level there was an IMAGES folder created
-rw-r--r--@  1 charlesl  domain users  220724885 Aug 21 13:00 9780323508902_epub.epub
drwxr-xr-x   8 charlesl  domain users        272 Aug 21 13:53 Anesthesia
drwxr-xr-x  44 charlesl  domain users       1496 Aug 21 13:53 IMAGES

2014-B-032:Elsevier charlesl$ cd Anesthesia/
2014-B-032:Anesthesia charlesl$ ls -l
total 5472
drwxr-xr-x    4 charlesl  domain users      136 Aug 21 13:53 IMAGES
-rw-r--r--    1 charlesl  domain users  2785868 Aug 21 13:53 ace.json
drwxr-xr-x  104 charlesl  domain users     3536 Aug 21 13:53 data
drwxr-xr-x    4 charlesl  domain users      136 Aug 21 13:53 js
-rw-r--r--    1 charlesl  domain users     8991 Aug 21 13:53 report.html

BTW there was no IMAGES directory under data like I saw in another report, so I am confused on where these files are going

I wasn't expecting the IMAGES folder outside of the output folder I specified.  Other EPUBs I have tested with didn't have this behavior.

**Comment by rdeltour** [comment]
Thank you Charles for the report. I was kinda expecting this could happen in some cases, see #18.

Can you please send me an EPUB sample to reproduce the issue?

**Comment by clapierre** [comment]
Got permission and sent @rdeltour link to EPUB privately.
