### ISSUE TITLE
Milestones inquiry

### ISSUE THREAD

**Issue by rickj** [daisy/ace-core#36]
Is https://github.com/daisy/ace-core/milestones still current, or is there a more updated location for this information?

**Comment by rdeltour** [comment]
Hi @rickj.

Yeah the milestones are our official work plan but as you can see we got late (my bad) and missed P3. The idea now is to group P3 and P4 and publish early next week. Prototypes always were movable targets, the fixed deadline is the beta(s) and public releases.

I'll update the milestone right now to better reflect the current plan.

**Comment by rdeltour** [comment]
FYI, we decided today to release another prototype before the public beta (coming real soon now). The first public beta is moved to Oct 10.
