### ISSUE TITLE
Link to KB invalid

### ISSUE THREAD

**Issue by clapierre** [daisy/ace-core#37]
In a 0.20 report a link to
https://daisy.github.io/a11y-kb/docs/scripting/aria.html
is invalid.
Looks like it has been renamed to
https://daisy.github.io/a11y-kb/docs/script/aria.html

**Comment by marisademeglio** [comment]
The code has already been updated to reflect the new URL so the next release will reflect it:
https://github.com/daisy/ace-core/blob/master/src/report/axe2ace.js

**Comment by clapierre** [comment]
Thanks
